"""Change semester code

Revision ID: 03a9415ea2b5
Revises: 813737d72429
Create Date: 2025-04-18 18:12:42.062733

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "03a9415ea2b5"
down_revision: Union[str, None] = "813737d72429"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_subjects", sa.Column("semester_code", sa.Integer(), nullable=False)
    )
    op.drop_column("user_subjects", "semester_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_subjects",
        sa.Column("semester_name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("user_subjects", "semester_code")
    # ### end Alembic commands ###
