"""Add grade in application

Revision ID: 04b4a6e5fb25
Revises: 0b8fe6fc2c43
Create Date: 2025-07-21 18:36:31.959918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04b4a6e5fb25'
down_revision: Union[str, None] = '0b8fe6fc2c43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('grade', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'grade')
    # ### end Alembic commands ###
