"""full_name

Revision ID: 066acb8f4c32
Revises: 19f358ad780b
Create Date: 2025-06-21 16:48:07.697201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '066acb8f4c32'
down_revision: Union[str, None] = '19f358ad780b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('third_name', sa.String(), nullable=True))
    op.drop_column('applications', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('applications', 'third_name')
    op.drop_column('applications', 'last_name')
    op.drop_column('applications', 'first_name')
    # ### end Alembic commands ###
