"""Changed tasks table

Revision ID: 0b8fe6fc2c43
Revises: 0ec8eee991b6
Create Date: 2025-07-17 17:36:30.127561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b8fe6fc2c43'
down_revision: Union[str, None] = '0ec8eee991b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE student_activity_scores 
        ALTER COLUMN academic_performance TYPE INTEGER USING academic_performance::integer
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_activity_scores', 'academic_performance',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
