"""Add grant type columns

Revision ID: 0ec8eee991b6
Revises: 4e6b0c2ceee7
Create Date: 2025-07-17 16:25:00.934071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ec8eee991b6'
down_revision: Union[str, None] = '4e6b0c2ceee7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE student_activity_scores 
        ALTER COLUMN reading_culture TYPE INTEGER USING reading_culture::integer,
        ALTER COLUMN five_initiatives TYPE INTEGER USING five_initiatives::integer,
        ALTER COLUMN discipline_compliance TYPE INTEGER USING discipline_compliance::integer,
        ALTER COLUMN competition_achievements TYPE INTEGER USING competition_achievements::integer,
        ALTER COLUMN attendance_punctuality TYPE INTEGER USING attendance_punctuality::integer,
        ALTER COLUMN enlightenment_lessons TYPE INTEGER USING enlightenment_lessons::integer,
        ALTER COLUMN volunteering TYPE INTEGER USING volunteering::integer,
        ALTER COLUMN cultural_visits TYPE INTEGER USING cultural_visits::integer,
        ALTER COLUMN healthy_lifestyle TYPE INTEGER USING healthy_lifestyle::integer,
        ALTER COLUMN other_spiritual_activity TYPE INTEGER USING other_spiritual_activity::integer
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_activity_scores', 'other_spiritual_activity',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('student_activity_scores', 'healthy_lifestyle',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('student_activity_scores', 'cultural_visits',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('student_activity_scores', 'volunteering',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('student_activity_scores', 'enlightenment_lessons',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('student_activity_scores', 'attendance_punctuality',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('student_activity_scores', 'competition_achievements',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('student_activity_scores', 'discipline_compliance',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('student_activity_scores', 'five_initiatives',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('student_activity_scores', 'reading_culture',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
