"""full_name

Revision ID: 19f358ad780b
Revises: 51dccb723f2d
Create Date: 2025-06-21 16:09:45.187555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19f358ad780b'
down_revision: Union[str, None] = '51dccb723f2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'applications',
        sa.Column('full_name', sa.String(), nullable=True)
    )

    # 2. NULL qiymatlarni to‘ldiramiz
    op.execute("UPDATE applications SET full_name = 'Anonim' WHERE full_name IS NULL;")

    # 3. Endi ustunni nullable=False qilib o‘zgartiramiz
    op.alter_column(
        'applications',
        'full_name',
        existing_type=sa.String(),
        nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
