"""Add gpa column in user _2

Revision ID: 2766e33c09b6
Revises: c64979f7d644
Create Date: 2025-08-04 18:05:25.310383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2766e33c09b6'
down_revision: Union[str, None] = 'c64979f7d644'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_gpas')
    op.add_column('users', sa.Column('gpa', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gpa')
    op.create_table('user_gpas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gpa', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('educationYear', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('subjects', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('level', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('credit_sum', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('debt_subjects', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_gpas_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_gpas_pkey')
    )
    # ### end Alembic commands ###
