"""Add response file path

Revision ID: 27ab54201e42
Revises: 7d3b9e082eda
Create Date: 2025-06-23 19:01:07.407111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27ab54201e42'
down_revision: Union[str, None] = '7d3b9e082eda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('reponse_file', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'reponse_file')
    # ### end Alembic commands ###
