"""change status

Revision ID: 28fd6158ffed
Revises: 04b4a6e5fb25
Create Date: 2025-08-01 14:20:56.140298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28fd6158ffed'
down_revision: Union[str, None] = '04b4a6e5fb25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('student_status', sa.String(), nullable=True))
    op.drop_column('users', 'studentStatus')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('studentStatus', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'student_status')
    # ### end Alembic commands ###
