"""Add grant type columns

Revision ID: 4e6b0c2ceee7
Revises: 71e0e9543ad8
Create Date: 2025-07-17 16:07:46.378481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e6b0c2ceee7'
down_revision: Union[str, None] = '71e0e9543ad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('grant_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'grant_type')
    # ### end Alembic commands ###
