"""Add full_name

Revision ID: 51dccb723f2d
Revises: 0cb141035d21
Create Date: 2025-06-20 14:46:04.693267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51dccb723f2d'
down_revision: Union[str, None] = '0cb141035d21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('full_name', sa.String(), nullable=False))
    op.drop_column('applications', 'last_name')
    op.drop_column('applications', 'third_name')
    op.drop_column('applications', 'first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('third_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('applications', 'full_name')
    # ### end Alembic commands ###
