"""Change sore model 

Revision ID: 71e0e9543ad8
Revises: 625dbc111a8f
Create Date: 2025-07-09 16:35:49.569771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71e0e9543ad8'
down_revision: Union[str, None] = '625dbc111a8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_activity_scores', sa.Column('reading_culture_path', sa.String(), nullable=True))
    op.add_column('student_activity_scores', sa.Column('five_initiatives_path', sa.String(), nullable=True))
    op.add_column('student_activity_scores', sa.Column('academic_performance_path', sa.String(), nullable=True))
    op.add_column('student_activity_scores', sa.Column('discipline_compliance_path', sa.String(), nullable=True))
    op.add_column('student_activity_scores', sa.Column('competition_achievements_path', sa.String(), nullable=True))
    op.add_column('student_activity_scores', sa.Column('attendance_punctuality_path', sa.String(), nullable=True))
    op.add_column('student_activity_scores', sa.Column('enlightenment_lessons_path', sa.String(), nullable=True))
    op.add_column('student_activity_scores', sa.Column('volunteering_path', sa.String(), nullable=True))
    op.add_column('student_activity_scores', sa.Column('cultural_visits_path', sa.String(), nullable=True))
    op.add_column('student_activity_scores', sa.Column('healthy_lifestyle_path', sa.String(), nullable=True))
    op.add_column('student_activity_scores', sa.Column('other_spiritual_activity_path', sa.String(), nullable=True))
    op.drop_index('ix_student_activity_scores_id', table_name='student_activity_scores')
    op.drop_constraint('student_activity_scores_user_id_key', 'student_activity_scores', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('student_activity_scores_user_id_key', 'student_activity_scores', ['user_id'])
    op.create_index('ix_student_activity_scores_id', 'student_activity_scores', ['id'], unique=False)
    op.drop_column('student_activity_scores', 'other_spiritual_activity_path')
    op.drop_column('student_activity_scores', 'healthy_lifestyle_path')
    op.drop_column('student_activity_scores', 'cultural_visits_path')
    op.drop_column('student_activity_scores', 'volunteering_path')
    op.drop_column('student_activity_scores', 'enlightenment_lessons_path')
    op.drop_column('student_activity_scores', 'attendance_punctuality_path')
    op.drop_column('student_activity_scores', 'competition_achievements_path')
    op.drop_column('student_activity_scores', 'discipline_compliance_path')
    op.drop_column('student_activity_scores', 'academic_performance_path')
    op.drop_column('student_activity_scores', 'five_initiatives_path')
    op.drop_column('student_activity_scores', 'reading_culture_path')
    # ### end Alembic commands ###
