"""Add filepath and create_date

Revision ID: 7d3b9e082eda
Revises: 65a4cce2e2ab
Create Date: 2025-06-23 13:44:18.016564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d3b9e082eda'
down_revision: Union[str, None] = '65a4cce2e2ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('filepath', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('create_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'create_date')
    op.drop_column('applications', 'filepath')
    # ### end Alembic commands ###
