"""First revision

Revision ID: a3b7588a3d69
Revises:
Create Date: 2025-04-15 15:53:43.606594

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a3b7588a3d69"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("third_name", sa.String(), nullable=True),
        sa.Column("full_name", sa.String(), nullable=True),
        sa.Column("student_id_number", sa.String(), nullable=True),
        sa.Column("image_path", sa.String(), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("passport_pin", sa.String(), nullable=True),
        sa.Column("passport_number", sa.String(), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("password", sa.String(), nullable=True),
        sa.Column("gender", sa.String(), nullable=True),
        sa.Column("university", sa.String(), nullable=True),
        sa.Column("specialty", sa.String(), nullable=True),
        sa.Column("studentStatus", sa.String(), nullable=True),
        sa.Column("educationForm", sa.String(), nullable=True),
        sa.Column("educationType", sa.String(), nullable=True),
        sa.Column("paymentForm", sa.String(), nullable=True),
        sa.Column("group", sa.String(), nullable=True),
        sa.Column("educationLang", sa.String(), nullable=True),
        sa.Column("faculty", sa.String(), nullable=True),
        sa.Column("level", sa.String(), nullable=True),
        sa.Column("semester", sa.String(), nullable=True),
        sa.Column("address", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "achievements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("award_date", sa.Date(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("file_path", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "certs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("language", sa.String(length=50), nullable=False),
        sa.Column("certificate_type", sa.String(length=50), nullable=False),
        sa.Column("level", sa.String(length=10), nullable=False),
        sa.Column("series_and_number", sa.String(length=50), nullable=False),
        sa.Column("date_of_issue", sa.Date(), nullable=False),
        sa.Column("file_path", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "researchs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("form", sa.String(), nullable=False),
        sa.Column("pub_date", sa.Date(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("file_path", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_gpas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("gpa", sa.Float(), nullable=False),
        sa.Column("educationYear", sa.String(), nullable=False),
        sa.Column("subjects", sa.Integer(), nullable=False),
        sa.Column("level", sa.String(), nullable=False),
        sa.Column("credit_sum", sa.String(), nullable=False),
        sa.Column("debt_subjects", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_gpas")
    op.drop_table("researchs")
    op.drop_table("certs")
    op.drop_table("achievements")
    op.drop_table("users")
    # ### end Alembic commands ###
