"""Add student activaity

Revision ID: d92817677b3d
Revises: 4f5cac475bc7
Create Date: 2025-06-26 16:55:38.497224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd92817677b3d'
down_revision: Union[str, None] = '4f5cac475bc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_activity_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reading_culture', sa.Integer(), nullable=True),
    sa.Column('five_initiatives', sa.Integer(), nullable=True),
    sa.Column('academic_performance', sa.Integer(), nullable=True),
    sa.Column('discipline_compliance', sa.Integer(), nullable=True),
    sa.Column('competition_achievements', sa.Integer(), nullable=True),
    sa.Column('attendance_punctuality', sa.Integer(), nullable=True),
    sa.Column('enlightenment_lessons', sa.Integer(), nullable=True),
    sa.Column('volunteering', sa.Integer(), nullable=True),
    sa.Column('cultural_visits', sa.Integer(), nullable=True),
    sa.Column('healthy_lifestyle', sa.Integer(), nullable=True),
    sa.Column('other_spiritual_activity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_activity_scores_id'), 'student_activity_scores', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_activity_scores_id'), table_name='student_activity_scores')
    op.drop_table('student_activity_scores')
    # ### end Alembic commands ###
