"""change status

Revision ID: fbaf3ac8d720
Revises: 6e6992c982d2
Create Date: 2025-08-01 14:23:59.799932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbaf3ac8d720'
down_revision: Union[str, None] = '6e6992c982d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('education_form', sa.String(), nullable=True))
    op.add_column('users', sa.Column('education_type', sa.String(), nullable=True))
    op.add_column('users', sa.Column('payment_form', sa.String(), nullable=True))
    op.add_column('users', sa.Column('education_lang', sa.String(), nullable=True))
    op.drop_column('users', 'educationForm')
    op.drop_column('users', 'educationType')
    op.drop_column('users', 'educationLang')
    op.drop_column('users', 'paymentForm')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('paymentForm', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('educationLang', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('educationType', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('educationForm', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'education_lang')
    op.drop_column('users', 'payment_form')
    op.drop_column('users', 'education_type')
    op.drop_column('users', 'education_form')
    # ### end Alembic commands ###
